In [10]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12],
              [13, 14, 15]])

print(f"shape of A: {A.shape}")

b = np.array([10, 20, 30, 40, 50]).reshape(-1, 1)
print(f"shape of b: {b.shape}")

print(f"result of broadcasted addition:\n{A + b}")

shape of A: (5, 3)
shape of b: (5, 1)
result of broadcasted addition:
[[11 12 13]
 [24 25 26]
 [37 38 39]
 [50 51 52]
 [63 64 65]]
